### ISSUE TITLE
Warnings at compile

### ISSUE THREAD

**Issue by EATREVITPOOPCAD** [alvpickmans/multiversion-revit-plugin-sample#1]
Compiling this sample as is and I have the following errors:

`warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'RevitAPILink.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'RevitAPIUILink.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'RevitDB.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'RevitUI.dll' or one of its dependencies. The module was expected to contain an assembly manifest.`

I have the SDK installed and under it all of the DLLs show up  (Even ones with warnings above) See image below. Any ideas?
![EATREVITPOOPCAD_0-1632461278538](https://user-images.githubusercontent.com/91353212/134751242-b7dc935c-6894-44ff-b467-12b3b40e091f.png)

**Comment by alvpickmans** [comment]
Didn't come across that errors. One thing I would try is remove from your local `.nuget` directory any reference to Autodesk.Revit NuGet package and let VS to reinstall them again.

**Comment by EATREVITPOOPCAD** [comment]
This didn't exactly work but it put me on the right track, Thank you!

.nuget and .proj files format still confuse the hell out of me compared to just referencing a **dll** through the UI, but here is how I got this to work:

- download **Revit_All_Main_Versions_API_x64** .nuget and install to VS each version you need ( I had to install them one at a time to this project & overwrite last reference
- remove last .nugget reference installed to the project
- in **.csproj** file go to the item group where it says `<PackageReference Include="Autodesk.Revit.SDK" Version="2021.*" Condition=" '$(RevitVersion)' == '2021' " PrivateAssets="All" />` and change to ` <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2021.*" Condition=" '$(RevitVersion)' == '2021' " PrivateAssets="All" /> ` do that for all the version you need to target

**Comment by alvpickmans** [comment]
Well, glad that you found a solution! The benefit of using NuGet package instead of referencing a dll from a local Revit installation is that it is easier to conditionally load one version from another, plus using NuGet package you don't necessary need to have Revit installed, although I admit making Revit addins without Revit is a shoot in the dark
